language: ruby
cache: bundler
rvm:
  - 2.3.0
  - 2.2.4
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - sudo add-apt-repository ppa:archivematica/externals -y
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

script: bundle exec rspec
