require_relative 'settings/transcoder'
require_relative 'settings/metadata'
require_relative 'settings/set_value_item'
require_relative 'settings/display_item'
require_relative 'settings/key_container'
require_relative 'settings/application'
